Match with state - fixes #121
domn1995/dunet pull request #133
Opened 2023-03-29 21:34 UTC by panoukos41

Hey @domn1995 I have created an implementation that should provide a solution for #121 that generates `Variant` & `Specific` `Match` methods that accept custom state eg:

```csharp
// Variant
public abstract TMatchOutput Match<TState, TMatchOutput>(TState state, ...);
public abstract void `Match<TState>(TState state, ...);

// Specific
public abstract TMatchOutput MatchSpecific<TState, TMatchOutput>(TState state ...);
public abstract void MatchSpecific<TState>(TState state ...);
```

I am also creating this as a draft since I would like some guidance about the tests and implementation.

For the implementation: I implemented the state methods together with the non-state ones but I could also move them to a different method. I just thought they belong together with their non-state counterparts.

For the tests: I know I could change some tests that execute methods to also execute the state counterpart or I could create a new test class that does just that but I am not sure which way to go 😄

2023-03-29 21:45 UTC, domn1995 commented
Thanks for the contribution! I'll take a look at this later today :)

2023-03-30 00:56 UTC, domn1995 commented
> For the implementation: I implemented the state methods together with the non-state ones but I could also move them to a different method. I just thought they belong together with their non-state counterparts.

I think this works well right now. The source builder is getting pretty long, but we can clean that up as a separate pull request later 👍

> For the tests: I know I could change some tests that execute methods to also execute the state counterpart or I could create a new test class that does just that but I am not sure which way to go 

My gut says to split it up into its own "state matching" test class. This way, we don't couple any of the existing test suites to the new one. Let me know if you need any help with those tests. :)

2023-03-30 08:06 UTC, panoukos41 commented
Thanks for your fast response and sorry for not getting back quickly It was midnight here in Greece 🇬🇷.

I will give it a try later today and if I have trouble finding which tests to mimic I will let you know 😁

2023-03-31 17:10 UTC, panoukos41 commented
@domn1995 I pushed the tests let me know if something needs changing or how I could help more 😄 otherwise :shipit:! (always wanted to use this emoji :D)

2023-04-01 01:43 UTC, domn1995 requested changes

2023-04-01 01:43 UTC, domn1995 commented on src/UnionGeneration/UnionSourceBuilder.cs
> +﻿using System.Net.NetworkInformation;
```suggestion
```
Looks like a rogue import

2023-04-01 01:43 UTC, domn1995 approved these changes

2023-04-01 01:45 UTC, domn1995 commented
Everything look awesome! Thanks again for the contribution! :shipit: :shipit: :shipit:

2023-04-01 01:46 UTC, merged